In [2]:
import torch

In [12]:
f = torch.load('embedding_wp8k.h5', map_location=torch.device('cpu'))
f

{'MAD': {'token': array(['[BOS]', '[EOS]', '[PAD]', ..., b'buk', b'bukoh', b'akon'],
        dtype=object),
  'embedding': {256: {'state': OrderedDict([('out_embed.weight',
                  tensor([[ 0.2864, -0.1880,  0.4790,  ..., -0.6662,  0.2594,  0.2970],
                          [ 0.4400,  0.3668, -0.7854,  ...,  0.2977,  0.3648,  0.3609],
                          [ 0.0272, -0.1218,  0.0727,  ..., -0.0525,  0.0379, -0.0847],
                          ...,
                          [-0.0176,  0.9952, -0.7156,  ..., -0.1078,  0.2166,  0.0465],
                          [-0.5162,  0.3528, -0.1197,  ...,  0.4175,  0.1526, -0.5871],
                          [ 0.5072, -0.8843, -0.0355,  ..., -0.9969,  0.1043,  0.7853]])),
                 ('in_embed.weight',
                  tensor([[ 0.5008,  0.8122, -0.2001,  ..., -0.1233, -0.7974,  0.1168],
                          [ 0.8682,  0.6445, -0.0164,  ...,  0.3475, -0.5600,  0.3920],
                          [ 0.6040, -0.0240, -0.2540

In [4]:
f['MAD']['embedding'][512]['state']['in_embed.weight']

tensor([[ 0.2013,  0.0599, -0.5636,  ..., -0.9809, -0.0742, -0.9718],
        [ 0.4336,  0.2279,  0.7211,  ...,  0.5350,  0.9851, -0.0799],
        [-0.8662, -0.6195, -0.0163,  ..., -0.3977,  0.2754,  0.5548],
        ...,
        [-0.2075, -0.3110, -0.3013,  ...,  0.6450, -1.4559, -0.2960],
        [ 0.2286,  0.9402, -0.6818,  ...,  0.3404,  0.3274,  0.1785],
        [ 0.5539, -0.5770, -0.7320,  ..., -0.1426, -0.4321,  0.3029]])

In [13]:
f['IND']['embedding'][512]['state']['in_embed.weight'].shape[0]

8004

In [21]:
t = f['TEKS'][89]
[f['MAD']['token'][x] for x in t[0] if x != 2], \
[f['IND']['token'][x] for x in t[1] if x != 2]

(['[BOS]',
  b'd\xcc\xa3i',
  b"_'-",
  b'_an',
  b"_d\xcc\xa3i'",
  b'bha\xcc\x82ra\xcc\x82',
  b'_ng',
  b'se\xcc\x80',
  b"ta'",
  b'kenne\xcc\x80ng',
  b'e\xcc\x80',
  b'_angghuy',
  '[EOS]'],
 ['[BOS]', b'tidak', b'melihat', '[EOS]'])